background = 0xFF1A1B26
base = 0xFF292E42
text = 0xFFC0CAF5
alternate_base = 0xFF24283B
bright_text = 0xFF7AA2F7
accent = 0xFF7AA2F7
link_text = 0xFF7AA2F7
accent_secondary = 0xFF7DCFFF
font_family = "IBM Plex Mono"
font_family_monospace = "monospace"
font_size = 13
small_font_size = 10
rounding_large = 8
rounding_small = 4

