# Argvus palette
# ---
# bg         "#1A1B26"
# bg-2       "#16161E"
# ui         "#292E42"
# ui-2       "#3B4261"
# ui-3       "#404552"
# tx-3       "#565F89"
# tx-2       "#A9B1D6"
# tx         "#C0CAF5"
# red-400     "#F7768E" re
# orange-400  "#E0AF68" or
# yellow-400  "#A9B1D6" ye
# yellow-600  "#E0AF68" ye-2
# green-400   "#7AA2F7" gr
# cyan-400    "#7AA2F7" cy
# cyan-600    "#172D3D" cy-2
# cyan-700    "#172D3D" cy-700
# cyan-900    "#101C28" cy-900
# blue-400    "#7AA2F7" bl
# purple-400  "#7DCFFF" pu
# magenta-400 "#F7768E" ma

[app]
overall = { bg = "#1A1B26" } # bg

[mgr]
cwd = { fg = "#C0CAF5", bold = true } # tx

# Find
find_keyword = { fg = "#7AA2F7", reversed = true } # cy
find_position = { fg = "#7AA2F7", bold = true, italic = true } # cy

# Marker
marker_copied = { fg = "#7AA2F7", bg = "#7AA2F7" } # gr, gr
marker_cut = { fg = "#F7768E", bg = "#F7768E" } # re, re
marker_marked = { fg = "#172D3D", bg = "#172D3D" } # cy-700, cy-700
marker_selected = { fg = "#7AA2F7", bg = "#7AA2F7" } # cy, cy

# Count
count_copied = { fg = "#7AA2F7", bold = true, reversed = true } # gr
count_cut = { fg = "#F7768E", bold = true, reversed = true } # re
count_selected = { fg = "#7AA2F7", bold = true, reversed = true } # cy

# Border
border_symbol = "│"
border_style = { fg = "#292E42" } # ui

[indicator]
parent = { underline = true }
current = { fg = "#C0CAF5", bg = "#292E42" } # tx, ui
preview = { underline = true }
padding = { open = "█", close = "█" }

[tabs]
active = { fg = "#C0CAF5", bg = "#404552", bold = true } # tx, ui-3
inactive = { fg = "#A9B1D6", bg = "#292E42" } # tx-2, ui
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode]
# Normal mode
normal_main = { fg = "#C0CAF5", bg = "#404552", bold = true } # tx, ui-3
normal_alt = { fg = "#A9B1D6", bg = "#292E42" } # tx-2, ui

# Select mode
select_main = { fg = "#1A1B26", bg = "#7AA2F7", bold = true } # bg, cy
select_alt = { fg = "#7AA2F7", bg = "#101C28" } # cy, cy-900

# Unset mode
unset_main = { fg = "#1A1B26", bg = "#7AA2F7", bold = true } # bg, cy
unset_alt = { fg = "#7AA2F7", bg = "#101C28" } # cy, cy-900

[status]
overall = { fg = "#C0CAF5" } # tx

# Permissions
perm_type = { fg = "#7AA2F7" } # bl
perm_read = { fg = "#A9B1D6" } # ye
perm_write = { fg = "#F7768E" } # re
perm_exec = { fg = "#7AA2F7" } # gr
perm_sep = { fg = "#A9B1D6" } # tx-2

# Progress
progress_label = { fg = "#1A1B26" } # bg
progress_normal = { fg = "#7AA2F7", bg = "#172D3D" } # cy, cy-700
progress_error = { bg = "#F7768E" } # re

[which]
cols = 3
mask = { bg = "#16161E" } # bg-2
cand = { fg = "#7AA2F7", bold = true } # cy
rest = { fg = "#7AA2F7", italic = true } # cy
desc = { fg = "#565F89" } # tx-3
separator = " "
separator_style = { }

[confirm]
border = { fg = "#404552" } # ui-3
title = { fg = "#565F89", bold = true } # tx-3
body = { fg = "#C0CAF5", bold = true } # tx
list = { fg = "#C0CAF5" } # tx
btn_yes = { fg = "#C0CAF5", bg = "#404552", bold = true } # tx, ui-3
btn_no = { fg = "#A9B1D6", bg = "#292E42" } # tx-2, ui

[spot]
border = { fg = "#404552" } # ui-3
title = { fg = "#565F89", bold = true } # tx-3
tbl_col = { fg = "#A9B1D6" } # tx-2
tbl_cell = { fg = "#C0CAF5", bg = "#292E42" } # tx, ui

[notify]
# Notification title
title_info = { fg = "#7AA2F7" } # bl
title_warn = { fg = "#E0AF68" } # or
title_error = { fg = "#F7768E" } # re

[pick]
border = { fg = "#404552", bold = true } # ui-3
active = { fg = "#C0CAF5" } # tx
inactive = { fg = "#A9B1D6" } # tx-2

[input]
border = { fg = "#404552" } # ui-3
title = { fg = "#565F89", bold = true } # tx-3
value = { fg = "#C0CAF5" } # tx
selected = { bg = "#16161E" } # bg-2

[cmp]
border = { fg = "#404552", bold = true } # ui-3
active = { fg = "#C0CAF5", bg = "#292E42" } # tx, ui
inactive = { fg = "#A9B1D6" } # tx-2

[tasks]
border = { fg = "#404552" } # ui-3
title = { fg = "#565F89", bold = true } # tx-3
hovered = { fg = "#C0CAF5", bg = "#292E42" } # tx, ui

[help]
on = { fg = "#7AA2F7" } # bl
run = { fg = "#7AA2F7" } # cy
desc = { fg = "#565F89", italic = true } # tx-3
hovered = { bg = "#292E42" } # ui
footer = { fg = "#1A1B26", bg = "#7AA2F7", bold = true } # bg, cy

[filetype]
rules = [
  # Empty files
  { mime = "inode/empty", fg = "#565F89" }, # tx-3

  # Special files
  { url = "*", is = "orphan", fg = "#565F89" }, # tx-3
  { url = "*/", is = "orphan", fg = "#565F89" }, # tx-3
  { url = "*", is = "link", fg = "#7AA2F7" }, # cy
  { url = "*/", is = "link", fg = "#7AA2F7" }, # cy
  { url = "*", is = "block", fg = "#C0CAF5" }, # tx
  { url = "*", is = "char", fg = "#C0CAF5" }, # tx
  { url = "*", is = "fifo", fg = "#F7768E" }, # ma
  { url = "*", is = "sock", fg = "#F7768E" }, # ma
  { url = "*", is = "sticky", fg = "#C0CAF5" }, # tx
  { url = "*", is = "dummy", fg = "#565F89" }, # tx-3

  # Fallback
  { url = "*/", fg = "#C0CAF5" }, # tx
  { url = "*", is = "exec", fg = "#7AA2F7" }, # gr
  { url = "*", fg = "#A9B1D6" } # tx-2
]

[icon]
dirs = [
  { name = ".config", text = "", fg = "#7AA2F7" }, # cy
  { name = ".git", text = "", fg = "#7AA2F7" }, # cy
  { name = ".github", text = "", fg = "#7AA2F7" }, # cy
  { name = ".npm", text = "", fg = "#7AA2F7" }, # cy
  { name = "Desktop", text = "", fg = "#7AA2F7" }, # cy
  { name = "Development", text = "", fg = "#7AA2F7" }, # cy
  { name = "Documents", text = "", fg = "#7AA2F7" }, # cy
  { name = "Downloads", text = "", fg = "#7AA2F7" }, # cy
  { name = "Library", text = "", fg = "#7AA2F7" }, # cy
  { name = "Movies", text = "", fg = "#7AA2F7" }, # cy
  { name = "Music", text = "", fg = "#7AA2F7" }, # cy
  { name = "Pictures", text = "", fg = "#7AA2F7" }, # cy
  { name = "Public", text = "", fg = "#7AA2F7" }, # cy
  { name = "Videos", text = "", fg = "#7AA2F7" } # cy
]
conds = [
  # Special files
  { if = "orphan", text = "", fg = "#565F89" }, # tx-3
  { if = "link", text = "", fg = "#7AA2F7" }, # cy
  { if = "block", text = "", fg = "#C0CAF5" }, # tx
  { if = "char", text = "", fg = "#C0CAF5" }, # tx
  { if = "fifo", text = "", fg = "#F7768E" }, # ma
  { if = "sock", text = "", fg = "#F7768E" }, # ma
  { if = "sticky", text = "", fg = "#C0CAF5" }, # tx
  { if = "dummy", text = "", fg = "#565F89" }, # tx-3

  # Fallback
  { if = "dir", text = "", fg = "#7AA2F7" }, # cy
  { if = "exec", text = "", fg = "#7AA2F7" }, # gr
  { if = "!dir", text = "", fg = "#A9B1D6" } # tx-2
]
