# ===================================
#  Hyprlock 0.9+
#  File: ~/.config/hypr/hyprlock.conf
#  Theme: tokyo-night
# ===================================

background {
  monitor =
  path = ~/.cache/argvus/hypr/hyprlock-wallpaper-blur.png
  blur_size = 3
  blur_passes = 3
  brightness = 0.55
}

input-field {
  monitor =
  size = 280, 45
  outline_thickness = 1
  outer_color = rgb(7AA2F7)
  inner_color = rgb(1A1B26)
  font_color = rgb(C0CAF5)
  placeholder_text = <i><span font_family='Symbols Nerd Font Mono'></span>  __ARGVUS_LOCK_PASSWORD__</i>
  position = 0, -100
  halign = center
  valign = center
  rounding = 6
}

shape {
  monitor =
  size = 320, 150
  color = rgba(17, 19, 22, 0.68)
  rounding = 12
  position = 0, 83
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%H:%M")"
  color = rgba(223, 229, 234, 0.82)
  font_size = 64
  font_family = IBM Plex Mono
  position = 0, 100
  halign = center
  valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%a, %d %B"
    color = rgba(176, 191, 203, 0.78)
    font_size = 18
    font_family = IBM Plex Mono
    position = 0, 40
    halign = center
    valign = center
}
